spring:
    application:
        name: Process payments

camunda:
  client:
    mode: selfManaged
    zeebe:
      enabled: true
      grpc-address: http://127.0.0.1:26500
      rest-address: http://127.0.0.1:8080
